name: declarative_navigation
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  app_settings: ^5.1.1
  build_runner: ^2.4.13
  camera: ^0.11.0+2
  change_app_package_name: ^1.4.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  location: ^7.0.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
